version: "3"
services:

  pg:
    image: postgres:9.6
    restart: always
    #Required env: POSTGRES_USER, POSTGRES_PASSWORD
    env_file: .env
    ports:
      - "5432:5432"

  api:
    image: taridocker/bn-api:latest
    depends_on:
          - pg
    env_file: .env
    ports:
      - "$API_PORT:$API_PORT"

  web:
    image: taridocker/bn-web:latest
    depends_on:
          - api
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"

  curl:
    image: tutum/curl

